from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ExperienceClimbAssets: 


	# Image Rule Assets
	# 活动通用挑战图标 
	I_ACT_FIRE = RuleImage(roi_front=(1132,602,88,54), roi_back=(1080,530,192,190), threshold=0.8, method="Template matching", file="./tasks/ExperienceClimb/as/as_act_fire.png")


